backend:
  name: github
  repo: Nikkekokeilee/kme-sivusto
  branch: main
  auth_type: implicit
  app_id: YOUR_GITHUB_APP_ID

local_backend: true

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Sivut"
    folder: "src/data/pages"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Nimi", name: "title", widget: "string" }
      - { label: "Lead-teksti", name: "lead", widget: "markdown" }
      - label: "Sisältö"
        name: "content"
        widget: "markdown"
